from app import db
from app.models import Themes, BookThemes, Books
# db.session.add(Themes(theme='Arte, cine y fotografía', language='es'))
# db.session.add(Themes(theme='Biografías, diarios y hechos reales', language='es'))
# db.session.add(Themes(theme='Ciencia, tecnología y medicina', language='es'))
# db.session.add(Themes(theme='Cómics y manga', language='es'))
# db.session.add(Themes(theme='Libros de consulta', language='es'))
# db.session.add(Themes(theme='Deportes', language='es'))
# db.session.add(Themes(theme='Derecho', language='es'))
# db.session.add(Themes(theme='Economía y empresa', language='es'))
# db.session.add(Themes(theme='Fantasía y ciencia ficción', language='es'))
# db.session.add(Themes(theme='Guías de estudio y repaso', language='es'))
# db.session.add(Themes(theme='Historia y filosofía', language='es'))
# db.session.add(Themes(theme='Hogar, manualidades y estilo de vida', language='es'))
# db.session.add(Themes(theme='Humor', language='es'))
# db.session.add(Themes(theme='Infantil', language='es'))
# db.session.add(Themes(theme='Informática, internet y medios digitales', language='es'))
# db.session.add(Themes(theme='Juvenil', language='es'))
# db.session.add(Themes(theme='Lengua, lingüística y redacción', language='es'))
# db.session.add(Themes(theme='Libros de texto', language='es'))
# db.session.add(Themes(theme='Guías de viaje', language='es'))
# db.session.add(Themes(theme='Ficción', language='es'))
# db.session.add(Themes(theme='Policíaca, negra y suspense', language='es'))
# db.session.add(Themes(theme='Política', language='es'))
# db.session.add(Themes(theme='Religión', language='es'))
# db.session.add(Themes(theme='Romántica', language='es'))
# db.session.add(Themes(theme='Salud, familia y desarrollo personal', language='es'))
# db.session.add(Themes(theme='Sociedad y ciencias sociales', language='es'))
# db.session.add(Themes(theme='Otros', language='es'))
#
# db.session.add(Themes(theme='Art, movies and photography', language='en'))
# db.session.add(Themes(theme='Biographies, diaries and real stories', language='en'))
# db.session.add(Themes(theme='Science, technology and medicine', language='en'))
# db.session.add(Themes(theme='Comics and manga', language='en'))
# db.session.add(Themes(theme='Reference books', language='en'))
# db.session.add(Themes(theme='Sports', language='en'))
# db.session.add(Themes(theme='Law', language='en'))
# db.session.add(Themes(theme='Economy and business', language='en'))
# db.session.add(Themes(theme='Fantasy and sci-fi', language='en'))
# db.session.add(Themes(theme='Study guides and recap', language='en'))
# db.session.add(Themes(theme='History and philosophy', language='en'))
# db.session.add(Themes(theme='Home, crafts and lifestyle', language='en'))
# db.session.add(Themes(theme='Humor', language='en'))
# db.session.add(Themes(theme='Childhood', language='en'))
# db.session.add(Themes(theme='Informatics, internet and digital media', language='en'))
# db.session.add(Themes(theme='Juvenile', language='en'))
# db.session.add(Themes(theme='Language, literature and composition', language='en'))
# db.session.add(Themes(theme='Text books', language='en'))
# db.session.add(Themes(theme='Travel guides', language='en'))
# db.session.add(Themes(theme='Fiction', language='en'))
# db.session.add(Themes(theme='Detectives, crime and suspense', language='en'))
# db.session.add(Themes(theme='Politics', language='en'))
# db.session.add(Themes(theme='Religion', language='en'))
# db.session.add(Themes(theme='Romantic', language='en'))
# db.session.add(Themes(theme='Health, family and personal development', language='en'))
# db.session.add(Themes(theme='Society and social sciences', language='en'))
# db.session.add(Themes(theme='Others', language='en'))


# db.session.commit()
#Books.query.delete()
#Themes.query.delete()

print(Themes.query.all())
print(Books.query.all())
#db.session.commit()

