from app import db
from app.models import Themes, BookThemes, Books
# db.session.add(Themes(id='1', theme='Arte, cine y fotografía'))
# db.session.add(Themes(id='2', theme='Biografías, diarios y hechos reales'))
# db.session.add(Themes(id='3', theme='Ciencias, tecnología y medicina'))
# db.session.add(Themes(id='4', theme='Cómics y manga'))
# db.session.add(Themes(id='5', theme='Consulta'))
# db.session.add(Themes(id='6', theme='Deporte'))
# db.session.add(Themes(id='7', theme='Derecho'))
# db.session.add(Themes(id='8', theme='Economía y empresa'))
# db.session.add(Themes(id='9', theme='Fantasía y ciencia ficción'))
# db.session.add(Themes(id='10', theme='Guías de estudio y repaso'))
# db.session.add(Themes(id='11', theme='Historia'))
# db.session.add(Themes(id='12', theme='Hogar, manualidades y estilos de vida'))
# db.session.add(Themes(id='13', theme='Humor'))
# db.session.add(Themes(id='14', theme='Infantil'))
# db.session.add(Themes(id='15', theme='Informática, internet y medios digitales'))
# db.session.add(Themes(id='16', theme='Juvenil'))
# db.session.add(Themes(id='17', theme='Lengua, lingüística y redacción'))
# db.session.add(Themes(id='18', theme='Libros de texto'))
# db.session.add(Themes(id='19', theme='Libros y guías de viaje'))
# db.session.add(Themes(id='20', theme='Literatura y ficción'))
# db.session.add(Themes(id='21', theme='Policíaca, negra y suspense'))
# db.session.add(Themes(id='22', theme='Política'))
# db.session.add(Themes(id='23', theme='Religión'))
# db.session.add(Themes(id='24', theme='Romántica'))
# db.session.add(Themes(id='25', theme='Salud, familia y desarrollo personal'))
# db.session.add(Themes(id='26', theme='Sociedad y ciencias sociales'))
# db.session.add(Themes(id='27', theme='Otros'))
# db.session.commit()
#Books.query.delete()
#BookThemes.query.delete()
print(Books.query.all())
print(BookThemes.query.all())
#db.session.commit()
