"""empty message

Revision ID: 1e7123cc89de
Revises: 
Create Date: 2018-04-12 13:17:53.555729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7123cc89de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_language'), 'book', ['language'], unique=False)
    op.create_index(op.f('ix_book_name'), 'book', ['name'], unique=True)
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_theme'), 'themes', ['theme'], unique=True)
    op.create_table('book__themes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'theme_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book__themes')
    op.drop_index(op.f('ix_themes_theme'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_book_name'), table_name='book')
    op.drop_index(op.f('ix_book_language'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
